services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: cityguide2024/backend
    volumes:
      - ./backend/src:/app/src
    healthcheck:
      test: 'curl --fail --request POST --header ''content-type: application/json'' --url ''http://localhost:4000'' --data ''{"query":"query { __typename }"}'' || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: cityguide2024/frontend
    command: npm start
    restart: always
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      backend:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
  imagesupload:
    build:
      context: ./imagesupload
      dockerfile: Dockerfile.prod
    image: cityguide2024/imagesupload
    volumes:
      - ./imagesupload/src:/app/src
      - ./imagesupload/uploads:/app/uploads
  adminer:
    image: adminer
    ports:
      - 8080:8080
  gateway:
    image: nginx
    ports:
      - 7000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    depends_on:
      - frontend
volumes:
  pgdata:
