name: e2e_test

on: push

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run interface test
        run: docker compose -f docker-compose.yml up --build --exit-code-from e2e