name: e2e_test

on: push

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run interface test
        run: docker compose up --build 